name: flutter_date_time_picker
description: A Flutter package for date and time picker.
version: 2.3.0
homepage: https://iconica.nl/

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.17.0 <0.19.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
